@AICorporation.Api_HostAddress = http://localhost:5094

GET {{AICorporation.Api_HostAddress}}/weatherforecast/
###
GET http://localhost:5094/Company/

###

POST http://localhost:5094/Company/buy-warehouse
Accept: application/json
Content-Type: application/json

{
  "name": "siemaneczko",
  "type": 2
}


###
